version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.24.0
    ports:
      - 4444:4444
      - 4443:4443
      - 4442:4442

  chrome:
    image: selenium/node-chrome:4.24
    shm_size: 2gb
    deploy:
      replicas: 2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1

  edge:
    image: selenium/node-edge:4.24
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1

  edge_video:
    image: selenium/video:ffmpeg-7.0.2-20240922
    volumes:
      - /assets/videos:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      #      - FILE_NAME=edge_video.mp4
      - SE_VIDEO_FILE_NAME=auto

  firefox:
    image: selenium/node-firefox:4.24
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1